spring:
  application:
    name: spring-security-demo
    group: com.example
    version: 1.0.0
  lifecycle:
    timeout-per-shutdown-phase: 1m
  threads:
    virtual:
      enabled: true
  devtools:
    add-properties: false
    livereload:
      enabled: false
    restart:
      enabled: false

server:
  port: 8080
  servlet:
    context-path: /api
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /management
    access:
      default: none
  endpoint:
    health:
      access: read_only

logging:
  level:
    com.example.demo: debug
